# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 05:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answers')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Перевірено'), ('R', 'Відправлено на доопрацювання'), ('W', 'Очікує перевірки')], default='W', max_length=3)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('step_type', models.CharField(choices=[('L', 'Лекція'), ('D', 'Диктант'), ('T', 'Тест'), ('I', 'Самостійна робота')], max_length=1)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('sequence_number', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_steps', to='courser.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=15000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='dictations')),
                ('show_results', models.BooleanField(default=False)),
                ('course_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courser.CourseStep')),
            ],
        ),
        migrations.CreateModel(
            name='DictationSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(max_length=15000)),
                ('comparison_result', models.TextField(max_length=15000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('errors_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courser.Dictation')),
            ],
        ),
        migrations.CreateModel(
            name='IndependentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=15000)),
                ('course_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courser.CourseStep')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=15000)),
                ('course_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courser.CourseStep')),
            ],
        ),
        migrations.AddField(
            model_name='answerfile',
            name='independent_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courser.IndependentWork'),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
